[tool.poetry]
name = "poetry-instance"
version = "2.1.3"
description = ""
authors = []
license = ""
package-mode = false

[tool.poetry.dependencies]
python = "3.13.5"
poetry = "2.1.3"

[tool.poetry.group.additional.dependencies]
poetry-pyinstaller-plugin = "^1.4.0"
poetry-exec-plugin = "^1.0.1"

