[tool.poetry]
name = "poetry-instance"
version = "2.1.4"
description = ""
authors = []
license = ""
package-mode = false

[tool.poetry.dependencies]
python = "3.13.5"
poetry = "^2.1.4"

[tool.poetry.group.additional.dependencies]
poetry-exec-plugin = "^1.0.1"
poetry-pyinstaller-plugin = "^1.4.0"

