[tool.poetry]
name = "poetry-instance"
version = "2.1.3"
description = ""
authors = []
license = ""
package-mode = false

[tool.poetry.dependencies]
python = "3.13.3"
poetry = "2.1.3"

[tool.poetry.group.additional.dependencies]
poetry-plugin-exec = "^1.0.4"

