remote_id = '1881536'
kb_layout_type = 'Not ISO'
size = [
    0,
    0,
    0,
    0,
]
fav = []

[options]
remote-menubar-drag-right = '1.0'
theme = 'dark'
remote-menubar-drag-left = '0.0'

[ui_flutter]
peer-sorting = 'Remote ID'
peer-tab-index = '0'
