"$schema" = 'https://starship.rs/config-schema.json'

add_newline=true

palette = "custom"

format = """
[╭─](gray)\
$all\
[╰─](gray)\
$character"""

[character]
error_symbol = '[⨉](bold red)'

[directory]
home_symbol='/home/tyler'

[cmd_duration]
disabled=false
show_milliseconds=true
format='test'

[palettes.custom]
gray = "#808080"
